<!DOCTYPE html>
<html>
    <head>
        <title>Error Page of Phone Book</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="css/style.css">
    </head>

    <body>

        <div align="center">
        <h2 color="red">Error page</h2>

        <p> <b>URL:</b> ${url}
        <p> <b>Exception:</b> ${exception}

        </div>

        <div class="footer" align="center">
                <p><a href="/">Home Page</a>
                <p>
                <p><a href="phonebook">Show Phone Book</a>
                <p>
                <p><a href="phonebookPDF">Create Phone Book in PDF</a>
                <p>
                <p><a href="uploadStatic.html">Upload Phone Book</a>
        </div>
    </body>

</html>
